server:
  port: 8082

spring:
  application:
    name: fraud
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/fraud
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true